repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/doublier/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--all', '--', '--check']
      - id: cargo-check
      - id: clippy
        args: ['--', '-D', 'warnings']
